openapi: 3.1.0
info:
  title: 影片處理 API
  version: 1.0.0
  description: 用於處理影片轉錄和高亮標記的 API

paths:
  /api/process-video:
    post:
      summary: 處理影片並生成轉錄
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                video:
                  type: string
                  format: binary
                  description: 上傳的影片檔案
              required:
                - video
      responses:
        "200":
          description: 成功處理影片
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      transcript:
                        type: object
                        properties:
                          sections:
                            type: array
                            items:
                              type: object
                              properties:
                                title:
                                  type: string
                                  example: Introduction
                                startTime:
                                  type: integer
                                  example: 0
                                endTime:
                                  type: integer
                                  example: 15
                                sentences:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      text:
                                        type: string
                                        example: Welcome to our product demonstration.
                                      startTime:
                                        type: string
                                        example: "00:00"
                                      endTime:
                                        type: string
                                        example: "00:05"
                                      isHighlight:
                                        type: boolean
                                        example: false
                            example:
                              - title: "Introduction"
                                startTime: 0
                                endTime: 15
                                sentences:
                                  - text: "Welcome to our product demonstration."
                                    startTime: "00:00"
                                    endTime: "00:05"
                                    isHighlight: false
                                  - text: "Today, we'll be showcasing our latest innovation."
                                    startTime: "00:05"
                                    endTime: "00:15"
                                    isHighlight: true
                              - title: "Key Features"
                                startTime: 15
                                endTime: 40
                                sentences:
                                  - text: "Our product has three main features."
                                    startTime: "00:15"
                                    endTime: "00:20"
                                    isHighlight: false
                                  - text: "First, it's incredibly easy to use."
                                    startTime: "00:20"
                                    endTime: "00:25"
                                    isHighlight: false
                                  - text: "Second, it's highly efficient."
                                    startTime: "00:25"
                                    endTime: "00:30"
                                    isHighlight: false
                                  - text: "And third, it's cost-effective."
                                    startTime: "00:30"
                                    endTime: "00:40"
                                    isHighlight: false
                              - title: "Demonstration"
                                startTime: 40
                                endTime: 60
                                sentences:
                                  - text: "Let me show you how it works."
                                    startTime: "00:40"
                                    endTime: "00:45"
                                    isHighlight: false
                                  - text: "Simply press this button to start."
                                    startTime: "00:45"
                                    endTime: "00:50"
                                    isHighlight: true
                                  - text: "The interface is intuitive and user-friendly."
                                    startTime: "00:50"
                                    endTime: "01:00"
                                    isHighlight: true
                              - title: "Conclusion"
                                startTime: 60
                                endTime: 80
                                sentences:
                                  - text: "In conclusion, our product is a game-changer."
                                    startTime: "01:00"
                                    endTime: "01:05"
                                    isHighlight: false
                                  - text: "We're excited to bring this to market."
                                    startTime: "01:05"
                                    endTime: "01:10"
                                    isHighlight: true
                                  - text: "Thank you for your attention."
                                    startTime: "01:10"
                                    endTime: "01:20"
                                    isHighlight: false
                  message:
                    type: string
                    example: 處理成功

  /api/save-highlights:
    post:
      summary: 保存影片高亮標記
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                highlights:
                  type: array
                  items:
                    type: object
                    properties:
                      startTime:
                        type: string
                      endTime:
                        type: string
                      text:
                        type: string
              required:
                - highlights
      responses:
        "200":
          description: 成功保存高亮標記
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    example: 200
                  data:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                      highlights:
                        type: array
                        items:
                          type: object
                          properties:
                            startTime:
                              type: string
                              example: "00:05"
                            endTime:
                              type: string
                              example: "00:15"
                            text:
                              type: string
                              example: "Today, we'll be showcasing our latest innovation."
                  message:
                    type: string
                    example: 保存成功
